### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by gilesknap** [garethnisbet/T-BOTS#1]
Gareth,

Please, could you update the Readme.Md to include brief instructions on:-

1. Which Bluetooth app to use and how configure the trim buttons (with meaningful labels)

1. How to tune the motor deadbands

Thanks

(P.S. My TBot now has its new parts and looks very nice - it was fun to build, your mechanical design is very neat)

**Comment by garethnisbet** [comment]
Hi Giles, I haven't completed the documentation yet but here's what I have
on setting up the motors.
I left the remaining parts to make your T-Bot consistent  with the
production version on your desk.
Gareth

**Comment by gilesknap** [comment]
I think the attachment did not come through to the issue comment. Please, can you attach it or email me directly.

**Comment by garethnisbet** [comment]
The attachment is showing up in my sent mail. I have tried forwarding it to your diamond email.Gareth



Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Giles Knap <notifications@github.com> Date: 03/07/2018  19:36  (GMT+00:00) To: garethnisbet/T-BOTS <T-BOTS@noreply.github.com> Cc: garethnisbet <garethnisbet@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [garethnisbet/T-BOTS] Documentation (#1) 
I think the attachment did not come through to the issue comment. Please, can you attach it or email me directly.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/garethnisbet/T-BOTS","title":"garethnisbet/T-BOTS","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/garethnisbet/T-BOTS"}},"updates":{"snippets":[{"icon":"PERSON","message":"@gilesknap in #1: I think the attachment did not come through to the issue comment. Please, can you attach it or email me directly."}],"action":{"name":"View Issue","url":"https://github.com/garethnisbet/T-BOTS/issues/1#issuecomment-402253969"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/garethnisbet/T-BOTS/issues/1#issuecomment-402253969",
"url": "https://github.com/garethnisbet/T-BOTS/issues/1#issuecomment-402253969",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [garethnisbet/T-BOTS] Documentation (#1)",
"sections": [
{
"text": "",
"activityTitle": "**Giles Knap**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@gilesknap",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"garethnisbet/T-BOTS\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"garethnisbet/T-BOTS\",\n\"issueId\": 1\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/garethnisbet/T-BOTS/issues/1#issuecomment-402253969"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 352336057\n}"
}
],
"themeColor": "26292E"
}
]
