### ISSUE TITLE
New software - some issues

### ISSUE THREAD

**Issue by gilesknap** [garethnisbet/T-BOTS#2]
Hi Gareth,

I'm trying to update the firmware on the TBot.

The .ino file in folder TBot0.4 was called TBot0.3.ino and Arduino IDE complained. I renamed the file to TBot0.4.ino and it then did upload (however I am left uncertain as to whether you have put the correct file in source control. 

I tuned the deadbands and it seemed to work as expected but the bot cannot balance at all now!

**Comment by garethnisbet** [comment]
Sorry Giles, it is the correct one. I renamed the folder but forgot to rename the file before I uploaded it.
Gareth


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Giles Knap <notifications@github.com> Date: 16/07/2018  20:15  (GMT+00:00) To: garethnisbet/T-BOTS <T-BOTS@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [garethnisbet/T-BOTS] New software - some issues (#2) 
Hi Gareth,
I'm trying to update the firmware on the TBot.
The .ino file in folder TBot0.4 was called TBot0.3.ino and Arduino IDE complained. I renamed the file to TBot0.4.ino and it then did upload (however I am left uncertain as to whether you have put the correct file in source control.
I tuned the deadbands and it seemed to work as expected but the bot cannot balance at all now!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/garethnisbet/T-BOTS","title":"garethnisbet/T-BOTS","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/garethnisbet/T-BOTS"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"New software - some issues (#2)"}],"action":{"name":"View Issue","url":"https://github.com/garethnisbet/T-BOTS/issues/2"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/garethnisbet/T-BOTS/issues/2",
"url": "https://github.com/garethnisbet/T-BOTS/issues/2",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "New software - some issues (#2)",
"sections": [
{
"text": "",
"activityTitle": "**Giles Knap**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@gilesknap",
"facts": [
{
"name": "Repository: ",
"value": "garethnisbet/T-BOTS"
},
{
"name": "Issue #: ",
"value": 2
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"garethnisbet/T-BOTS\",\n\"issueId\": 2,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"garethnisbet/T-BOTS\",\n\"issueId\": 2\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/garethnisbet/T-BOTS/issues/2"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 356948521\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by garethnisbet** [comment]
Hi Giles, I just saw the second paragraph of your email.
Are all the deadband values positive? they should be. If the robot is not
balancing, subtract 5 from each of the deadband values.
Gareth

**Comment by gilesknap** [comment]
I think we need an mpsfactor per motor but it is a single global used in speedPIDCallBack. Perhaps we require a third. average mpsfactor for this function to use.

**Comment by gilesknap** [comment]
I've subtracted 5 from each (positive) deadband and still not balancing. It seems that mpsfactor is making it want to move the motors pretty fast. I saw a big jump in speed after applying mpsfactor in the test program.

**Comment by garethnisbet** [comment]
You can give different mpsfactor 's to each motor when you instantiate
them. I usually just multiply one of them with a scale factor to account
for the difference.
Gareth

**Comment by garethnisbet** [comment]
Is the mpsfactor around 250?

**Comment by gilesknap** [comment]
It is probably the trim values that are an issue. I'm pretty sure you did not tell me the name of the bluetooth app to use (I can't extract it from our email threads anyway)

_BTW if you follow the link in the GitHub emails and open these issues in the GitHub website it would mean attachments and formatting etc would work and we could then have the whole log of getting this working in one place._

**Comment by gilesknap** [comment]
Agreed re mps factor passing to motor constructors, but don't expect novice programmers to guess that. Your instructions should include details of how to transfer your findings in the test program over to the finished one (I'm sure that was going to be in the final product anyway!).

I think my issue is with trim numbers and it would be easy to check this if I had the bluetooth controller fully working. I've now found the app but I'm going to open another ticket on this subject (this is not being pedantic, it so I can easily find the answer again when I come back to this in a week with a wiped memory and will help anyone else if they end up coming to this repo for their TBOT code).

**Comment by gilesknap** [comment]
My mps values are a 230 and 218

**Comment by gilesknap** [comment]
A couple of other things to add to the documentation:-

- The board is an Arduino Nano and the IDE needs to be told via Tools->Board
- If you choose the Arduino IDE from Ubuntu Software, you will get a Snap which is a bit rubbish since it won't have permission to access the serial port
  - fix by doing 
    - `snap remove arduino-mhall119`
    - `snap install arduino-mhall119 --classic`
- your account will need access to the serial port, for ubuntu (and probably others):-
  - `sudo adduser <userid> dialout`
  - log out and back in

**Comment by gilesknap** [comment]
I've configured the controller but the trim buttons seem random as to whether they affect the associated value. I cannot get my bot to balance at all. I'm going to wait for the next release since there is no point in debugging something that you are rewriting.

**Comment by gilesknap** [comment]
I've installed the new version of the firmware and adjusted my gyro trim to -4.1 and all is now working well. I have pushed my settings to a new branch so you can review them.  See https://github.com/garethnisbet/T-BOTS/tree/gilesBot

Branches might be a nice way to manage the settings for each of your test robots. So you don't need to leave commented out settings in the code for each bot you are testing. I'll talk you through how if you are interested.

I'll bring my robot to work tomorrow so you can tell me if it is performing as expected (seems a little slower than I remember).

**Comment by garethnisbet** [comment]
Hi Giles, you can increase the speed by increasing controller_sensitivity.This will, however, increase the likelihood of falling over.
I'll bring my  T-Bot for comparison.
Gareth




Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Giles Knap <notifications@github.com> Date: 25/07/2018  22:24  (GMT+00:00) To: garethnisbet/T-BOTS <T-BOTS@noreply.github.com> Cc: Gareth Nisbet <garethnisbet@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [garethnisbet/T-BOTS] New software - some issues (#2) 
I've installed the new version of the firmware and adjusted my gyro trim to -4.1 and all is now working well. I have pushed my settings to a new branch so you can review them.  See https://github.com/garethnisbet/T-BOTS/tree/gilesBot
Branches might be a nice way to manage the settings for each of your test robots. So you don't need to leave commented out settings in the code for each bot you are testing. I'll talk you through how if you are interested.
I'll bring my robot to work tomorrow so you can tell me if it is performing as expected (seems a little slower than I remember).

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/garethnisbet/T-BOTS","title":"garethnisbet/T-BOTS","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/garethnisbet/T-BOTS"}},"updates":{"snippets":[{"icon":"PERSON","message":"@gilesknap in #2: I've installed the new version of the firmware and adjusted my gyro trim to -4.1 and all is now working well. I have pushed my settings to a new branch so you can review them.  See https://github.com/garethnisbet/T-BOTS/tree/gilesBot\r\n\r\nBranches might be a nice way to manage the settings for each of your test robots. So you don't need to leave commented out settings in the code for each bot you are testing. I'll talk you through how if you are interested.\r\n\r\nI'll bring my robot to work tomorrow so you can tell me if it is performing as expected (seems a little slower than I remember)."}],"action":{"name":"View Issue","url":"https://github.com/garethnisbet/T-BOTS/issues/2#issuecomment-407900757"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/garethnisbet/T-BOTS/issues/2#issuecomment-407900757",
"url": "https://github.com/garethnisbet/T-BOTS/issues/2#issuecomment-407900757",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [garethnisbet/T-BOTS] New software - some issues (#2)",
"sections": [
{
"text": "",
"activityTitle": "**Giles Knap**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@gilesknap",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"garethnisbet/T-BOTS\",\n\"issueId\": 2,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"garethnisbet/T-BOTS\",\n\"issueId\": 2\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/garethnisbet/T-BOTS/issues/2#issuecomment-407900757"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 356948521\n}"
}
],
"themeColor": "26292E"
}
]
